# Generated by Django 5.2.12 on 2026-03-05 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0004_classgroup_join_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='chapters',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sections',
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('SY', 'Programme'), ('CH', 'Chapitre'), ('SE', 'Partie'), ('LE', 'Leçon'), ('QU', 'Quiz'), ('EX', 'Exercice')], max_length=2)),
                ('public', models.BooleanField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('grade_level', models.CharField(choices=[('SE', 'Seconde'), ('PR', 'Première'), ('TE', 'Terminale')], max_length=2)),
                ('difficulty', models.IntegerField(choices=[(1, 'Seconde'), (2, 'Première'), (3, 'Terminale')])),
                ('subject', models.CharField(choices=[('MA', 'Mathématiques'), ('PH', 'Physique'), ('CO', 'Numérique et sciences informatiques')], max_length=2)),
                ('content', models.JSONField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassGroupSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField()),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.classgroup')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.node')),
            ],
            options={
                'unique_together': {('class_group', 'node')},
            },
        ),
        migrations.CreateModel(
            name='NodeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='courses.node')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='courses.node')),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
        migrations.AddField(
            model_name='node',
            name='children',
            field=models.ManyToManyField(related_name='parents', through='courses.NodeNode', through_fields=('parent', 'child'), to='courses.node'),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
