# Generated by Django 5.2.12 on 2026-03-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_section_chapters_remove_item_sections_node_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Facile'), (2, 'Moyen'), (3, 'Difficile')]),
        ),
    ]
