# Generated by Django 5.2.10 on 2026-02-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_title_item_name_remove_item_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('LESSON', 'Lesson'), ('EXAMPLE', 'Example'), ('EXERCICE', 'Exercice'), ('QUIZZ', 'Quizz')], default='LESSON', max_length=8),
            preserve_default=False,
        ),
    ]
