# Generated by Django 5.2.12 on 2026-03-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_node_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroupsyllabus',
            name='order_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='content',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, 'Facile'), (2, 'Moyen'), (3, 'Difficile')], null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('SE', 'Seconde'), ('PR', 'Première'), ('TE', 'Terminale')], max_length=2),
        ),
        migrations.AlterField(
            model_name='node',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='subject',
            field=models.CharField(blank=True, choices=[('MA', 'Mathématiques'), ('PH', 'Physique'), ('CO', 'Numérique et sciences informatiques')], max_length=2),
        ),
        migrations.AlterField(
            model_name='nodenode',
            name='order_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
