# Generated by Django 5.2.11 on 2026-02-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('LESSON', 'Lesson'), ('EXERCICE', 'Exercice'), ('QUIZZ', 'Quizz')], max_length=8),
        ),
    ]
