# Generated by Django 5.2.11 on 2026-02-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_section_description_alter_item_item_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='title',
        ),
    ]
