# Generated by Django 5.2.12 on 2026-03-30 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_classgroupsyllabus_order_index_and_more'),
        ('users', '0006_alter_membership_class_group_alter_membership_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroupsyllabus',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_links', to='users.classgroup'),
        ),
        migrations.AlterField(
            model_name='classgroupsyllabus',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_group_links', to='courses.node'),
        ),
    ]
