# Generated by Django 5.2.13 on 2026-04-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_classgroupsyllabus_class_group_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NodeNode',
            new_name='NodeLink',
        ),
    ]
