# Generated by Django 5.2.13 on 2026-04-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_nodenode_nodelink'),
        ('users', '0006_alter_membership_class_group_alter_membership_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='authorized_groups',
            field=models.ManyToManyField(blank=True, related_name='authorized_nodes', to='users.classgroup'),
        ),
    ]
