# Generated by Django 5.2.14 on 2026-05-12 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_node_authorized_groups'),
        ('records', '0002_alter_attempt_node_alter_attempt_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NS', 'Non commencé'), ('IP', 'En cours'), ('CO', 'Terminé')], default='NS', max_length=2)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='courses.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'node')},
            },
        ),
    ]
