# Generated by Django 5.2.14 on 2026-05-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='in_progress_at',
            field=models.DateTimeField(null=True),
        ),
    ]
