# Generated by Django 5.2.12 on 2026-03-04 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_classgroup_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status', models.CharField(choices=[('ME', 'Membre'), ('AD', 'Administrateur')], max_length=2)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.classgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'class_group')},
            },
        ),
        migrations.AddField(
            model_name='classgroup',
            name='users',
            field=models.ManyToManyField(related_name='class_groups', through='users.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
