# Generated by Django 5.2.12 on 2026-03-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_membership_classgroup_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='join_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
