# Generated by Django 5.2.12 on 2026-03-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_section_chapters_remove_item_sections_node_and_more'),
        ('users', '0004_classgroup_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='syllabus',
            field=models.ManyToManyField(related_name='class_groups', through='courses.ClassGroupSyllabus', to='courses.node'),
        ),
    ]
