# Generated by Django 5.2.12 on 2026-03-30 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_classgroup_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='users.classgroup'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_group_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
