# Generated by Django 5.2.13 on 2026-04-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_membership_class_group_alter_membership_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='join_code',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, unique=True),
        ),
    ]
