# Generated by Django 5.2.10 on 2026-01-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='item',
            name='sections',
            field=models.ManyToManyField(to='courses.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='chapters',
            field=models.ManyToManyField(to='courses.chapter'),
        ),
    ]
