# Generated by Django 5.2.10 on 2026-01-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_delete_group_item_sections_section_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='Exemples de variables Integer', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='sections',
            field=models.ManyToManyField(related_name='items', to='courses.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='chapters',
            field=models.ManyToManyField(related_name='sections', to='courses.chapter'),
        ),
    ]
