# Generated by Django 5.2.10 on 2026-01-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_item_title_alter_item_sections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='file_path',
        ),
        migrations.AddField(
            model_name='item',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
